// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteUserByIdData, DeleteUserByIdErrors, DeleteUserByIdResponses, DownloadFileData, DownloadFileErrors, DownloadFileResponses, FileListData, FileListErrors, FileListResponses, GetCurrentUserData, GetCurrentUserErrors, GetCurrentUserResponses, GetUserByIdData, GetUserByIdErrors, GetUserByIdResponses, LoginData, LoginErrors, LoginResponses, OllamaChatData, OllamaChatErrors, OllamaChatResponses, OllamaChatStreamData, OllamaChatStreamErrors, OllamaChatStreamResponses, OllamaHealthCheckData, OllamaHealthCheckErrors, OllamaHealthCheckResponses, PostCreateUserData, PostCreateUserErrors, PostCreateUserResponses, PostUsersListData, PostUsersListErrors, PostUsersListResponses, PreviewFileData, PreviewFileErrors, PreviewFileResponses, RefreshData, RefreshErrors, RefreshResponses, UpdateUserInfosData, UpdateUserInfosErrors, UpdateUserInfosResponses, UploadFileData, UploadFileErrors, UploadFileResponses, UploadFilesData, UploadFilesErrors, UploadFilesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * 用户登录
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    responseType: 'json',
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 检查 Ollama 服务可用性
 *
 * 检查本地 Ollama 服务是否可用。
 */
export const ollamaHealthCheck = <ThrowOnError extends boolean = false>(options?: Options<OllamaHealthCheckData, ThrowOnError>) => (options?.client ?? client).get<OllamaHealthCheckResponses, OllamaHealthCheckErrors, ThrowOnError>({
    responseType: 'json',
    url: '/ollama/health',
    ...options
});

/**
 * 非流式对话
 *
 * 非流式接口：一次性返回完整回答。
 */
export const ollamaChat = <ThrowOnError extends boolean = false>(options: Options<OllamaChatData, ThrowOnError>) => (options.client ?? client).post<OllamaChatResponses, OllamaChatErrors, ThrowOnError>({
    responseType: 'json',
    url: '/ollama/chat',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 流式对话（调用 Ollama 云服务）
 */
export const ollamaChatStream = <ThrowOnError extends boolean = false>(options: Options<OllamaChatStreamData, ThrowOnError, unknown>) => (options.client ?? client).sse.post<OllamaChatStreamResponses, OllamaChatStreamErrors, ThrowOnError>({
    responseType: 'text',
    url: '/ollama/chat/stream',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 刷新获取 access_token
 */
export const refresh = <ThrowOnError extends boolean = false>(options: Options<RefreshData, ThrowOnError>) => (options.client ?? client).post<RefreshResponses, RefreshErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/refresh',
    ...options
});

/**
 * 获取当前登录用户
 *
 * 返回当前登录用户信息。
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserData, ThrowOnError>) => (options?.client ?? client).get<GetCurrentUserResponses, GetCurrentUserErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/getCurrentUser',
    ...options
});

/**
 * 根据用户 id 获取用户信息
 */
export const getUserById = <ThrowOnError extends boolean = false>(options: Options<GetUserByIdData, ThrowOnError>) => (options.client ?? client).get<GetUserByIdResponses, GetUserByIdErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/getUserById',
    ...options
});

/**
 * 用户分页列表
 *
 * 查询用户分页列表，支持分页、关键字模糊搜索和状态筛选。
 */
export const postUsersList = <ThrowOnError extends boolean = false>(options: Options<PostUsersListData, ThrowOnError>) => (options.client ?? client).post<PostUsersListResponses, PostUsersListErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/postUsersList',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 创建用户
 *
 * 创建新用户，并对明文密码进行哈希处理。
 */
export const postCreateUser = <ThrowOnError extends boolean = false>(options: Options<PostCreateUserData, ThrowOnError>) => (options.client ?? client).post<PostCreateUserResponses, PostCreateUserErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/postCreateUser',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 根据用户 id 删除用户
 */
export const deleteUserById = <ThrowOnError extends boolean = false>(options: Options<DeleteUserByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteUserByIdResponses, DeleteUserByIdErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/deleteUserById',
    ...options
});

/**
 * 根据用户 id 更新用户信息
 *
 * 按用户 ID 更新资料，支持局部更新和密码修改。
 */
export const updateUserInfos = <ThrowOnError extends boolean = false>(options: Options<UpdateUserInfosData, ThrowOnError>) => (options.client ?? client).patch<UpdateUserInfosResponses, UpdateUserInfosErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/updateUserInfos',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 预览文件
 *
 * 预览文件
 */
export const previewFile = <ThrowOnError extends boolean = false>(options: Options<PreviewFileData, ThrowOnError>) => (options.client ?? client).get<PreviewFileResponses, PreviewFileErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/files/preview/{file_id}',
    ...options
});

/**
 * 根据 fileId 下载单文件
 *
 * 下载单文件
 */
export const downloadFile = <ThrowOnError extends boolean = false>(options: Options<DownloadFileData, ThrowOnError>) => (options.client ?? client).get<DownloadFileResponses, DownloadFileErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/files/download/{file_id}',
    ...options
});

/**
 * 单文件上传
 *
 * 上传单文件并返回元数据
 */
export const uploadFile = <ThrowOnError extends boolean = false>(options: Options<UploadFileData, ThrowOnError>) => (options.client ?? client).post<UploadFileResponses, UploadFileErrors, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/files/uploadfile',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * 多文件上传
 *
 * 上传多文件并返回元数据
 */
export const uploadFiles = <ThrowOnError extends boolean = false>(options: Options<UploadFilesData, ThrowOnError>) => (options.client ?? client).post<UploadFilesResponses, UploadFilesErrors, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/files/uploadfiles',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * 根据 ids 获取文件分页列表
 */
export const fileList = <ThrowOnError extends boolean = false>(options: Options<FileListData, ThrowOnError>) => (options.client ?? client).post<FileListResponses, FileListErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/files/fileList',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
