// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}/api` | (string & {});
};

/**
 * Body_uploadFile
 */
export type BodyUploadFile = {
    /**
     * File
     *
     * 单文件
     */
    file: Blob | File;
};

/**
 * Body_uploadFiles
 */
export type BodyUploadFiles = {
    /**
     * Files
     *
     * 多文件
     */
    files: Array<Blob | File>;
};

/**
 * ChatRequest
 */
export type ChatRequest = {
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Stream
     */
    stream?: boolean;
};

/**
 * FileOut
 *
 * 上传文件的 API 响应模型.
 */
export type FileOut = {
    /**
     * Filename
     */
    filename: string;
    /**
     * File Path
     */
    file_path: string;
    /**
     * File Size
     */
    file_size: number;
    /**
     * Content Type
     */
    content_type: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginModel
 */
export type LoginModel = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * PageResult[FileOut]
 */
export type PageResultFileOut = {
    /**
     * Data
     */
    data: Array<unknown>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Pagesize
     */
    pageSize: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PageResult[UsersReo]
 */
export type PageResultUsersReo = {
    /**
     * Data
     */
    data: Array<UsersReo>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Pagesize
     */
    pageSize: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * ResponseModel[FileOut]
 */
export type ResponseModelFileOut = {
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: FileOut | null;
    /**
     * Success
     */
    success?: boolean;
};

/**
 * ResponseModel[PageResult[FileOut]]
 */
export type ResponseModelPageResultFileOut = {
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: PageResultFileOut | null;
    /**
     * Success
     */
    success?: boolean;
};

/**
 * ResponseModel[PageResult[UsersReo]]
 */
export type ResponseModelPageResultUsersReo = {
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: PageResultUsersReo | null;
    /**
     * Success
     */
    success?: boolean;
};

/**
 * ResponseModel[UsersLoginReo]
 */
export type ResponseModelUsersLoginReo = {
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: UsersLoginReo | null;
    /**
     * Success
     */
    success?: boolean;
};

/**
 * ResponseModel[UsersReo]
 */
export type ResponseModelUsersReo = {
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: UsersReo | null;
    /**
     * Success
     */
    success?: boolean;
};

/**
 * ResponseModel[list[FileOut]]
 */
export type ResponseModelListFileOut = {
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    /**
     * Data
     */
    data?: Array<FileOut> | null;
    /**
     * Success
     */
    success?: boolean;
};

/**
 * UsersCreate
 *
 * 创建用户时的入参模型。
 */
export type UsersCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email: string;
    /**
     * Phone
     */
    phone: string | null;
    /**
     * Disabled
     */
    disabled?: boolean;
    /**
     * Is Deleted
     */
    is_deleted?: boolean;
    /**
     * Avatar Id
     */
    avatar_id?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UsersLoginReo
 */
export type UsersLoginReo = {
    /**
     * Username
     */
    username: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email: string;
    /**
     * Phone
     */
    phone: string | null;
    /**
     * Disabled
     */
    disabled?: boolean;
    /**
     * Is Deleted
     */
    is_deleted?: boolean;
    /**
     * Avatar Id
     */
    avatar_id?: string | null;
    /**
     * Id
     */
    id: string | null;
    /**
     * Created At
     */
    created_at: string | null;
    /**
     * Updated At
     */
    updated_at: string | null;
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * UsersReo
 *
 * 用户信息返回模型。
 */
export type UsersReo = {
    /**
     * Username
     */
    username: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email: string;
    /**
     * Phone
     */
    phone: string | null;
    /**
     * Disabled
     */
    disabled?: boolean;
    /**
     * Is Deleted
     */
    is_deleted?: boolean;
    /**
     * Avatar Id
     */
    avatar_id?: string | null;
    /**
     * Id
     */
    id: string | null;
    /**
     * Created At
     */
    created_at: string | null;
    /**
     * Updated At
     */
    updated_at: string | null;
};

/**
 * UsersUpdate
 *
 * 更新用户时的入参模型，支持局部更新。
 */
export type UsersUpdate = {
    /**
     * Username
     */
    username?: string | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Disabled
     */
    disabled?: boolean | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Avatar Id
     */
    avatar_id?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * QueryRequest
 *
 * 用户分页列表查询参数。
 */
export type AppModelsFilesQueryRequest = {
    /**
     * Page
     *
     * 页码，从 1 开始
     */
    page?: number;
    /**
     * Pagesize
     *
     * 每页条数，默认 10，最大 100
     */
    pageSize?: number;
    /**
     * Ids
     *
     * ids 查询
     */
    ids?: Array<string> | null;
};

/**
 * QueryRequest
 *
 * 用户分页列表查询参数。
 */
export type AppModelsUsersQueryRequest = {
    /**
     * Page
     *
     * 页码，从 1 开始
     */
    page?: number;
    /**
     * Pagesize
     *
     * 每页条数，默认 10，最大 100
     */
    pageSize?: number;
    /**
     * Keyword
     *
     * 关键字模糊查询，匹配用户名、姓名、邮箱
     */
    keyword?: string | null;
    /**
     * Username
     *
     * 按用户名模糊查询
     */
    username?: string | null;
    /**
     * Full Name
     *
     * 按姓名模糊查询
     */
    full_name?: string | null;
    /**
     * Email
     *
     * 按邮箱模糊查询
     */
    email?: string | null;
    /**
     * Phone
     *
     * 按手机号模糊查询
     */
    phone?: string | null;
    /**
     * Disabled
     *
     * 按禁用状态精确筛选
     */
    disabled?: boolean | null;
};

export type LoginData = {
    body: LoginModel;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelUsersLoginReo;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type OllamaHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ollama/health';
};

export type OllamaHealthCheckErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type OllamaHealthCheckResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type OllamaChatData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/ollama/chat';
};

export type OllamaChatErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OllamaChatError = OllamaChatErrors[keyof OllamaChatErrors];

export type OllamaChatResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type OllamaChatStreamData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/ollama/chat/stream';
};

export type OllamaChatStreamErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OllamaChatStreamError = OllamaChatStreamErrors[keyof OllamaChatStreamErrors];

export type OllamaChatStreamResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RefreshData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Refresh Token
         */
        refresh_token: string;
    };
    url: '/users/refresh';
};

export type RefreshErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshError = RefreshErrors[keyof RefreshErrors];

export type RefreshResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelUsersLoginReo;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/getCurrentUser';
};

export type GetCurrentUserErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type GetCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelUsersReo;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type GetUserByIdData = {
    body?: never;
    path?: never;
    query: {
        /**
         * User Id
         */
        user_id: string;
    };
    url: '/users/getUserById';
};

export type GetUserByIdErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserByIdError = GetUserByIdErrors[keyof GetUserByIdErrors];

export type GetUserByIdResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelUsersReo;
};

export type GetUserByIdResponse = GetUserByIdResponses[keyof GetUserByIdResponses];

export type PostUsersListData = {
    body: AppModelsUsersQueryRequest;
    path?: never;
    query?: never;
    url: '/users/postUsersList';
};

export type PostUsersListErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostUsersListError = PostUsersListErrors[keyof PostUsersListErrors];

export type PostUsersListResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelPageResultUsersReo;
};

export type PostUsersListResponse = PostUsersListResponses[keyof PostUsersListResponses];

export type PostCreateUserData = {
    body: UsersCreate;
    path?: never;
    query?: never;
    url: '/users/postCreateUser';
};

export type PostCreateUserErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostCreateUserError = PostCreateUserErrors[keyof PostCreateUserErrors];

export type PostCreateUserResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelUsersReo;
};

export type PostCreateUserResponse = PostCreateUserResponses[keyof PostCreateUserResponses];

export type DeleteUserByIdData = {
    body?: never;
    path?: never;
    query: {
        /**
         * User Id
         */
        user_id: string;
    };
    url: '/users/deleteUserById';
};

export type DeleteUserByIdErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserByIdError = DeleteUserByIdErrors[keyof DeleteUserByIdErrors];

export type DeleteUserByIdResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelUsersReo;
};

export type DeleteUserByIdResponse = DeleteUserByIdResponses[keyof DeleteUserByIdResponses];

export type UpdateUserInfosData = {
    body: UsersUpdate;
    path?: never;
    query: {
        /**
         * User Id
         *
         * 用户 ID
         */
        user_id: string;
    };
    url: '/users/updateUserInfos';
};

export type UpdateUserInfosErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserInfosError = UpdateUserInfosErrors[keyof UpdateUserInfosErrors];

export type UpdateUserInfosResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelUsersReo;
};

export type UpdateUserInfosResponse = UpdateUserInfosResponses[keyof UpdateUserInfosResponses];

export type PreviewFileData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: string;
    };
    query?: never;
    url: '/files/preview/{file_id}';
};

export type PreviewFileErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PreviewFileError = PreviewFileErrors[keyof PreviewFileErrors];

export type PreviewFileResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DownloadFileData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: string;
    };
    query?: never;
    url: '/files/download/{file_id}';
};

export type DownloadFileErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadFileError = DownloadFileErrors[keyof DownloadFileErrors];

export type DownloadFileResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadFileData = {
    body: BodyUploadFile;
    path?: never;
    query?: never;
    url: '/files/uploadfile';
};

export type UploadFileErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFileError = UploadFileErrors[keyof UploadFileErrors];

export type UploadFileResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelFileOut;
};

export type UploadFileResponse = UploadFileResponses[keyof UploadFileResponses];

export type UploadFilesData = {
    body: BodyUploadFiles;
    path?: never;
    query?: never;
    url: '/files/uploadfiles';
};

export type UploadFilesErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFilesError = UploadFilesErrors[keyof UploadFilesErrors];

export type UploadFilesResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelListFileOut;
};

export type UploadFilesResponse = UploadFilesResponses[keyof UploadFilesResponses];

export type FileListData = {
    body: AppModelsFilesQueryRequest;
    path?: never;
    query?: never;
    url: '/files/fileList';
};

export type FileListErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FileListError = FileListErrors[keyof FileListErrors];

export type FileListResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelPageResultFileOut;
};

export type FileListResponse = FileListResponses[keyof FileListResponses];
